Flownative:
  Google:
    CloudStorage:
      profiles:
        # Default credentials and client options - override these in your settings with real values
        default:
          credentials:
            clientEmail: '123456789012-abc123defg456hijklmnopqrstuvwxyz@developer.gserviceaccount.com'

            # The private key (P12) can be specified in two ways: either by specifying the path and filename leading to
            # the file containing the key, or as a string with the P12 key (base64 encoded). If both options are set,
            # the "privateKeyP12" option wins.
            privateKeyP12PathAndFilename: 'Data/Secrets/MyGoogleProject-abc123457def.p12'
            privateKeyP12Base64Encoded: ''
      continuesFailureLimit: 50
