Flownative:
  Google:
    CloudStorage:
      profiles:
        # Default credentials and client options - override these in your settings with real values
        default:
          credentials:
            # The private key (JSON) can be specified in two ways: either by specifying the path and filename leading to
            # the file containing the key, or as a string with the JSON key data (base64 encoded). If both options are set,
            # the "privateKeyJson" option wins.
            privateKeyJsonPathAndFilename: 'Data/Secrets/MyGoogleProject-abc123457def.json'
            privateKeyJsonBase64Encoded: ''
